// <auto-generated />
namespace THOK.Wms.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class rename_system_to_systeminfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_system_to_systeminfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201407030250357_rename_system_to_systeminfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
