// <auto-generated />
namespace THOK.Wms.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class add_sort_supply_position : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_sort_supply_position));
        
        string IMigrationMetadata.Id
        {
            get { return "201408150829593_add_sort_supply_position"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
