// <auto-generated />
namespace THOK.Wms.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-beta1-30515")]
    public sealed partial class update_ef_to_6_1_1_beta_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_ef_to_6_1_1_beta_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201406180636307_update_ef_to_6_1_1_beta_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
