// <auto-generated />
namespace THOK.Wms.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class add_sms_alarm_info : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_sms_alarm_info));
        
        string IMigrationMetadata.Id
        {
            get { return "201409010913337_add_sms_alarm_info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
