// <auto-generated />
namespace THOK.Wms.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class update_wms_sort_order_dispatch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_wms_sort_order_dispatch));
        
        string IMigrationMetadata.Id
        {
            get { return "201408190206391_update_wms_sort_order_dispatch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
