// <auto-generated />
namespace THOK.Wms.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class add_pieces_quantity_and_bar_quantity_for_task : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_pieces_quantity_and_bar_quantity_for_task));
        
        string IMigrationMetadata.Id
        {
            get { return "201409220602234_add_pieces_quantity_and_bar_quantity_for_task"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
