// <auto-generated />
namespace THOK.Wms.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class update_sms_rename_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_sms_rename_change));
        
        string IMigrationMetadata.Id
        {
            get { return "201407080959130_update_sms_rename_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
