// <auto-generated />
namespace THOK.Wms.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class add_status_to_sms_sort_supply : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_status_to_sms_sort_supply));
        
        string IMigrationMetadata.Id
        {
            get { return "201409031304097_add_status_to_sms_sort_supply"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
